#+title: design goals
* Design Goals
Goals for the language (in no particular order and subject to community review):
- expressiveness :: the language should be flexible enough to communicate many
  different meanings and accomplish many different purposes,
- unambiguity :: utterances should have single meaning (though the meaning may
  be vague, in which case it will bear markers for the ways in which it is vague),
- semantic productivity,
- density :: expressions of the language should be concise,
- detail :: users should be able to convey a lot of information about the
  subject of discourse.

Additionally we will be guided by two Perl praxemes:
- There is more than one way to do it :: We aren't trying to make users
  think/speak one way or another. Instead, we provide the tools to make explicit
  which model a speaker is using.
- Make the easy things easy and the hard things possible :: Common expressions
  should be concise and require few inflections. As a correlate, vagueness
  should be the default, while allowing for the specific marking of exactness.
* Primary purpose of the language
@porpoiseless says:
#+begin_quote
1. This should be a language primarily for thinking about thinking.
   - Since thinking can have a variety of objects, this language must have
     ways of discussing many areas of human interest.
2. It should be rooted in phenomenology and methodology:
   - /What is it like/ to think about thinking?
   - /How do we go about/ thinking about thinking?
3. "Thinking about thinking" is already social. It requires at least two
   participants: the investigator and the investigated.
4. "Thinking about thinking" requires language (c.f. above and the
   [[https://plato.stanford.edu/entries/private-language/][private language argument]]).
   - Language or something equivalent. See how semiotics is devoured from within
     by linguistics. It seems like the latter should be a subset of the former,
     but in order to describe a symbol system we must turn it into language.
#+end_quote
