#+title: README
* The Free TNIL Project
Free TNIL is the working title of a community driven conlang inspired by [[http://ithkuil.net/][John Quijada's Ithkuil]].
It includes a refactoring of the category system developed by Mr. Quijada.

* Contributing
To contribute to this project:
1. clone this repo,
2. make a branch,
3. make your changes,
4. add your name to [[file:authors.txt][the authors list]],
5. submit a pull request.

* Design Goals
Goals for the language (in no particular order and subject to community review):
- expressiveness,
- unambiguity,
- semantic productivity,
- density,
- detail.

Additionally this project is an experiment in computer-aided language development, with a twist.
Alongside the usual tables of affixes and category values, these documents will contain programs for encoding and deciphering its text.
The end goal of this project is not only the specification of a language, but also an implementation of it.

* Description of the Language
Like other Philosophical/Ithkuilic languages, Free TNIL consists of a number of abstract categories marked morphologically on specific word-types.
[[file:docs/categories.org][This document]] outlines the categories of the language.
Morphology awaits the completion of the categories document.
