#+title: RFC: Back to Basics, or Organizational Sets
#+author: porpoiseless
* Problem
This document aims to address a cluster of related problems involving
the categories initially laid out by John Quijada in [[http://ithkuil.net/03_morphology.html#Sec3o6][Chapter 3: Basic
Morphology]] of /A Grammar of Ithkuil/ (AGOI), and to a lesser extent in
the periodic releases documenting The Next Ithkuilic Language
(TNIL). The three main issues we are attempting to resolve are as
follows:

1. Uncertainty exists around the licensing of terms used in AGOI. This
   may be a non-issue since Mr. Quijada has given written permission
   to use terms from AGOI with attribution. Nevertheless, it would be
   preferable to have a set of terms with an explicitly libre license
   for use in constructing philosophical languages.
2. Many grammatical items have confusing names or
   descriptions. Replacing these names with more conventional or
   intuitive ones and supplying documentation in accessible language
   can not only improve this situation, but incidentally solve the
   licensing problem.
3. Some categories have conceptual issues. For example some categories
   are unexpectedly non-orthogonal with each other, and some have a
   complex internal structure that could be made explicit.

* Duration
[2020-07-31 Fri]
* Current State
WIP Draft.
* Proposers
- @porpoiseless
* Detail
** Licensing Issues
The memo [[https://conlang.org/cms/wp-content/uploads/Dentons-Conlang-Memo-public-version.pdf][IP Protection for Constructed Languages]] discusses the legal
difficulties in claiming a language as IP. While documentary text be
protected, it doesn't appear that the name of a grammatical category
can be.

Attached is the text of an email Mr. Quijada sent in response to the
question of attribution for derived languages.

#+begin_quote
The only thing I require is that anyone basing their work on my own
should prominently display a disclaimer announcement in their
introduction or homepage, etc. stating that John Quijada’s Ithkuil
language is the basis and inspirational source for their own work. If
they borrow my morphological terminology, the disclaimer should state
such as well.

John Q. 
#+end_quote
** TODO Names and Jargon
- Many categories in Ithkuil have confusing names. 
** TODO conceptual issues with some categories
- Configuration and Perspective are non-orthogonal.
- 
- Perspective: what does it mean?
- Configuration has internal distinctions that are made more explicit
  in TNIL.
* Proposal
This document aims to answer the following question: What is the
minimal set of derivational categories that must be marked on words
formed from roots? In AGOI there are 6 derivational categories that
must marked on such words.

| Original term | Libre equivalent or replacement    |
|---------------+------------------------------------|
| Configuration | Number, Connectedness, Composition |
| Affiliation   | Disposition                        |
| Perspective   | Quantification, Distribution       |
| Extension     | Envelope                           |
| Essence       | [WIP]                              |
| Context       | Domain                             |
| Designation   | [TBD under Lexical categories]     |

Quijada makes frequent use in this chapter of the term,
"configurational set" which remains undefined throughout the
work. Formalizing this notion will allow for a more rigorous
interpretation of the language's semantics, and will help us write
better documentation.

** Organizational Categories
We rename "configurational set" to "organizational set" for three reasons:
1. the legal concerns already discussed,
2. "organization" better conveys the intent of the several categories
   involved than "configuration", and
3. this proposal eliminates Configuration in favor of the categories
   that logically constitute its meaning (Number, Connectedness,
   Composition).

Like Configurational Sets in Ithkuil and TNIL, Organizational sets are
a powerful way of expressing how a concept is instantiated in space
and time. An Organizational Set is a collection of instances of a root
marked for their number, proximity, and similarity.

| Category       | Values | Question                                                                 |
|----------------+--------+--------------------------------------------------------------------------|
| Number         |      4 | How many items in the set?                                               |
| Connectedness  |      3 | How closely are the items arranged?                                      |
| Composition    |      2 | Are the items physically similar?                                        |
|----------------+--------+--------------------------------------------------------------------------|
| Dispostition   |      4 | What is the use/purpose/intent of the items with respect to one another? |
| Distribution   |      2 | Is the set as a whole being discussed, or each member separately?        |
| Envelope       |     12 | What part of the set (or its members) is under consideration?            |
| Quantification |      2 | Is the speaker making an existential universal claim?                    |
| Vagueness      |      2 | Is the main term being used strictly or not?                             |

Number + Connectedness + Composition = 14 valid combinations

14*4*2*12*2*2 = 5376 combinations.

*** Number: How many instances are there?
Number, Connectedness, and Composition are not quite orthogonal to
each other because Connectedness and Composition cannot apply to
Singular or Non-Count sets. In addition to those Numbers, Dual and
Plural inflect for three values of Connectedness and two of
Composition, yielding fourteen valid combinations of Number,
Connectedness, and Composition.

| Number →                        | Non-Count | Singular |
|---------------------------------+-----------+----------|
| [No Composition, Connectedness] |           |          |
|---------------------------------+-----------+----------|
| Homogeneous                     | Dual      | Plural   |
|---------------------------------+-----------+----------|
| Isolated                        |           |          |
| Contiguous                      |           |          |
| Fused                           |           |          |
|---------------------------------+-----------+----------|
| Heterogeneous                   | Dual      | Plural   |
|---------------------------------+-----------+----------|
| Isolated                        |           |          |
| Contiguous                      |           |          |
| Fused                           |           |          |

**** Note on Non-Count and Defaults
The Non-Count number is the default and the most vague. Words marked with this
value are conceptualized as mass quantities where the units are irrelevant or
undisclosed. If language users wish to be more specific about the units, they
can choose another number. For example, Non-Count is used to speak about "some
water". If we are discussing a sensitive chemical process, it is entirely
possible that "some water" can be only one or two molecules. But if in our
discussion the individual quanta (and their homogeneity and connectedness)
become relevant, we should use a different number.

*** Connectedness: How physically close are the instances?

| Value      | Definition         |
|------------+--------------------|
| Isolated   | separate           |
| Contiguous | adjacent, touching |
| Fused      | attached, combined |

*** Composition: How varied are instances?

| Name          | Definition        |
|---------------+-------------------|
| Homogeneous   | uniform members   |
| Heterogeneous | diverse members   |

*** Disposition: How similar are the uses, purposes, or conditions of instances?

| Name         | Definition                     |
|--------------+--------------------------------|
| Ambivalent   | unknown/irrelevant use/purpose |
| Oppositional | divided/conflicted use/purpose |
| Mutual       | shared use/purpose             |
| Synergetic   | emergent use/purpose           |

*** Distribution: How does predication scope over members of the set?
Distribution is a logical category with no equivalent in Ithkuil or
TNIL. It governs whether operations are applied to individual items
from a set or to set itself. Another way to think about Distribution:
Conjunctive Distribution /singularizes/ the set.

| Value       | Definition               |
|-------------+--------------------------|
| Disjunctive | each instance separately |
| Conjunctive | all instances together   |


*** Envelope: What spatiotemporal part of the set is relevant?
Envelope identifies the spatiotemporal limits and dynamics of the set. 

| Value      | space                                    | time                     |
|------------+------------------------------------------+--------------------------|
| Partial    | part                                     | phase, moment, era of... |
| Holistic   | all                                      | (whole) duration of...   |
| Initial    | (spatial) beginning, first in a sequence | (beginning) beginning    |
| Terminal   | (spatial) end, last in a sequence        | (temporal) end           |
| Augmentive | physical/directional increase            | development/becoming     |
| Diminutive | physical/directional decrease            | decay/ceasing-to-be      |

**** TODO test scope order of envelope, distribution, and quantification
Envelope currently scopes outside of distribution. Thus, by varying
Distribution, we can refer to the beginning of the set, or the
beginning of each member of the set.

"The beginning of a group of cows..." vs. "A group of cow-beginnings..."

It might be necessary to give Distribution a few more values so it can
shuffle scope between Envelope and Quantification, 


*** Rethinking Perspective
In AGOI the category of Perspective is introduced by way of a
comparison to Number and Tense in natural languages. Perspective, the
documentation explains, describes "the manner in which [a formative]
is /spatio-temporally instantiated/".

**** Perspective in AGOI and TNIL
AGOI enumerates four values for this category, with separate
interpretations given to nouns and verbs in each.

- Monadic :: "spatio-temporally unified or accessible manifestation"
- Unbounded :: "temporally separated or inaccessible"
- Nomic :: "a generic collective entity or archetype, containing all
  members or instantiations of a configurative set throughout space
  and time (or within a specified spatio-temporal context)"
- Abstract :: "a configurative category into an abstract concept
  considered in a non-spatial, timeless, numberless context"

TNIL revises renames Unbounded to Polyadic and discards the notion of
"accessibility", thereby eliminating questions about /what/ is
spatio-temporally unified or separated from what. Monadic vs. Polyadic
now merely indicates singularity or plurality of the configurational
set.

As for the latter two categories, they are more conceptually
interesting but also more resistant to formalization. AGOI describes
Nomic sets as either a "collective entity" or "an archetype". Without
a clearer description of the use of this category, we are forced to
make guesses.

If a "collective entity" means "all the named items throughout
spacetime", then we might say, "The Dog has millions of legs". On the
other hand if by Nomic we mean to refer to the archetype, then we
might say, "The Dog takes up no space"--since surely the archetype of
"dog" is not a physical object. Another point is that Nomic is not
orthogonal to the Monadic vs. Polyadic distinction. Different speakers
may have different archetypes in mind. Philosophers, for example,
discuss "competing conceptions of the Good"; and while economists
blithely refer to "the Market", I am reminded of a professor of mine
who once said, "There is no Market, only markets."

Since "configurative set" implies a *collection* of the items named by
the root, we are always dealing with these *collections*. Until, that
is, we reach Nomic and Abstract. Monadic and Unbounded appear to deal
with groups of the type of thing named by the root they modify, but Nomic
and Abstract transform the type. 
 
Abstract may be even worse. Not only does it suffer from the same
non-orthogonality as Nomic, it appears to change the type of the word
it modifies. At least with Nomic we can employ the semantics of plural
logic and say that we are referring to all concrete instances. 

*** Quantification: 
Quoted from Ilmen on Discord, edited for formatting (removal of
message timestamps and addition of required punctuation).

#+begin_quote
Toaq is based on plural logics (a logic system which avoids explicitly
requiring the notion of sets to express plurality of things). From the
point of view of sets, it's as if all the nouns referred to sets,
singular nouns would be referring to singleton sets, and
predicates/verbs would all be fed with sets, and they would usually
make claim about the members of the sets and not about the sets
themselves (for sets are not very interesting in themselves, they're
abstract, they have membership and cardinality, and that's about all
there is to them); as a result, predicates are free to decide by
themselves to have a distributive or a collective usage of the sets
passed to them, it's up to the definition of the predicate, and is
indicated in the dictionary

As sets would be everywhere, they would be nowhere i.e. invisible. the
universal quantifier could be described as referring to the maximal
set of some given things and every possible subset of it cardinality
predicates ("X is onesome / one in number", "X are two in number" etc)
can be used to restrict the possible referents for the quantifiers:
"every cows which are two in number" ≈ "every pair of cows" there's
also an "X is/are among Y" which is homologuous to the subset relation
for sets ("X is equal to or a subset of Y") "every one among us wore a
hat" I seem to remember there was a funny picture for Lojban
illustrating the difference between "the students each wore a hat" and
"the students collectively wore a hat, i.e. a large hat covering all
the students at once"

#+end_quote

Quantification should be familiar to those with experience in predicate calculus.

| Value       | Definition                      |
|-------------+---------------------------------|
| Existential | "there exists...", at least one |
| Universal   | every instance                  |

Quantification and Distribution operate together:

|             | Disjunctive                                                  | Conjunctive                                                      |
|-------------+--------------------------------------------------------------+------------------------------------------------------------------|
| Existential | There is ("There is a pair of cows with eight legs [each].") | There is ("There is a pair of cows with eight legs [in total].") |
| Universal   | Each ("They each carried a stone.")                          | All ("They all carried a stone [together].")                     |

*** Vagueness: Is the root being used precisely?

| Value   | Definition                                                       |
|---------+------------------------------------------------------------------|
| Vague   | "something like", "what passes for"; questionable set membership |
| Precise | clear set membership                                             |


*** Scope order

#+begin_example
  vagueness(
    quantification(
      envelope(
        distribution(
          disposition(
            composition(
              connectedness(
                number(
                  root))))))))
#+end_example
* Record of votes
| Vote | Name   |
|------+--------|
| +1   | @uakci |
* Resolution
Draft.
* CC
