#+title: RFC: The Next Level, or Discourse Categories
#+author: porpoiseless
* Problem
Discourse categories in Ithkuil '11 provide a wealth of interesting
ideas. However, like the basic categories critiqued in [[file:RFC_0001.org][RFC 0001]], they
suffer from non-orthogonality. 
* Duration
[2020-07-31 Fri]
* Current State
WIP Draft.
* Proposers
- @porpoiseless
* Detail
** What is meant by a 'discourse category'?
Conversation relates two logically distinct contexts:
1. the content or subject matter of our our conversation, and
2. the people involved in having the conversation; speaker and
   audience plus the performative, rhetorical or communicative actions
   performed between them.

I will call the former 'content level' and the latter 'discourse
level'. While persons and events might coincide between these two
levels, they are indeed very different and the grammar of Ithkuil's
successor should reflect this fact.

As an extreme example of overlap between the contexts, someone might
make a sandwich and narrate to themselves every step of the
process: "I slice some bread. I spread peanut butter on one slice and
jelly on another slice..."

In this case, the same individual is the subject spoken about at the
content level, and both speaker and audience at the discourse
level. The former is a description of something in the world, in this
case the activity of the speaker as they assemble a sandwich, while
the latter is simply a person talking to themselves. We can change the
discourse context independently, for instance by having the speaker
use the same series of utterances as a demonstration or tutorial of
how to make a sandwich.

If the two contexts share persons or events, they can be often
distinguished by time, modalization, and role. We often speak about
our past or possible future selves. For example, when giving a
command, "(You) spread peanut butter on the bread", the content is a
possible future state where the addressee is performing the named
action. The discourse level is an instruction or command.

Even if, as in our example of narrating the assembly of a sandwich,
there is no difference in time and modalization, we can make the
distinction that at the content level there is a sandwich maker, and
at the discourse level there is a speaker and a listener. The fact
that all three are the same person in no way diminishes our ability to
differentiate what that person is doing in each role (making a
sandwich, vs. speaking/listening).


* Proposal

** Split Modality into Discourse & Content Levels 
#+caption: Queer Studies & Advanced Waxing (Community S6E4)
#+begin_quote
JEFF: Yeah, we really need wifi!

FRANKIE: Okay, let's not get carried away. We /need/ oxygen.

ELROY: We /have/ oxygen, we /need/ wifi!
#+end_quote

There are 3 sorts of modality in language, of which only one is
content level. Epistemic and Deontic modality refer respectively to
the speaker's certainty about the content, and the
normative/desiderative force embodied by the utterance. Alethic
modality relates to the modality of the content itself. Since alethic
modality is not a discourse level category, it belongs elsewhere in
the scope order.

Consider a sentence like, "They can't have children", which might be
interpreted as any of the three kinds of modality enumerated above.

#+CAPTION: Modalizing "They can't have children."
| Alethic   | They (biologically) aren't capable of having children. |
| Epistemic | Evidence suggests they don't have children.            |
| Deontic   | They ought not/shouldn't have children.                |

For each of these kinds of modality, we need a minimum of 3 modal
operators: actuality, possibility, and necessity. We can add more
specific modalities as needed: however, other grammatical machinery
can express meanings like, "I fear/hope they have children".

The Epistemic and Deontic modalities operate in tandem with other
discourse level categories.

Epistemic modality is associated with Evidentials--it expresses the
speaker's commitment to the knowledge embodied in their claims.

Deontic modality works with Illocution and Expectation to convey the
speaker's needs and desires. 

| alethic actuality     | being, reality                   |
| alethic possibility   | ability, capacity, or capability |
| alethic necessity     | need, requirement                |
|-----------------------+----------------------------------|
| epistemic actuality   | knowledge                        |
| epistemic possibility | doubt                            |
| epistemic necessity   | certainty                        |
|-----------------------+----------------------------------|
| deontic actuality     | is*                              |
| deontic possibility   | should/may                       |
| deontic necessity     | must                             |



* Record of votes
| Vote | Name          |
|------+---------------|
|   +1 | @porpoiseless |
* Resolution
Draft.
* CC
A list of persons to CC about this RFC.
