#+title: Free TNIL Categories
* Morphological Categories
Words in Free TNIL inflect for many categories. This document enumerates those categories and their values.

** Lexical items

*** Derivation
Each root has three stems and four Derivations.
Derivation selects a specific instantiation of a stem.

| Value   | Description                     |
|---------+---------------------------------|
| Content | material, interiority, "spirit" |
| Form    | shape, exteriority, "letter"    |
| Process | activity, effort                |
| Result  | intent, purpose                 |


*** Examples
| Lexical Item | Content                            | Form                               | Process                     | Result                                                       |
|--------------+------------------------------------+------------------------------------+-----------------------------+--------------------------------------------------------------|
| "fire"       | (to be) on fire, something burning | (to be) a flame                    | to burn, burning            | something burnt or heated by fire                            |
| "name"       | named item                         | name as a symbol                   | naming, to (give a) name    | identification                                               |
| "word"       | sense of a word                    | uttered/written/spoken/signed word | meaning, to mean            | referent of a word                                           |
| "stone"      | stone (as material)                | surface/shape of a stone           | stone-forming process       | something made of stone                                      |
| "emotion"    | experience an emotion              | express an emotion                 | cause an emotion            | psychological purpose of emotion or associated need/tendency |
| "machine"    | machine                            | design of a machine                | to construct a machine      | result of using a machine                                    |
| "disease"    | disease-causing agent, pathogen    | (to express) symptoms of a disease | to sicken, to cause disease | long term outcome, prognosis                                 |

** Organizational Categories
The "Organizational set" is a powerful way of expressing how a concept is instantiated in space and time.
The organizational set is represented morphologically by a consonantal affix.
| Category       | Values | Question                                                                 |
|----------------+--------+--------------------------------------------------------------------------|
| Number         |      3 | How many items in the set?                                               |
| Connectedness  |      3 | How closely are the items arranged?                                      |
| Composition    |      2 | Are the items physically similar?                                        |
| Dispostition   |      4 | What is the use/purpose/intent of the items with respect to one another? |
| Distribution   |      2 | Is the set as a whole being discussed, or each member separately?        |
| Envelope       |     12 | What part of the set (or its members) is under consideration?            |
| Quantification |      2 | Is the speaker making an existential universal claim?                    |
| Vagueness      |      2 | Is the main term being used strictly or not?                             |

Number, connectedness, and composition are tightly coupled with one another.
The categories of connectedness and composition cannot apply to Singular sets.
Consequently, for there are seven valid combinations of Number, Connectedness, Composition.

The 12 envelopes come in 2 series of six distinguished by whether they refer to space or time.
7*4*12*2*2*2=1344 values.

| homogeneous   | dual | plural |
|---------------+------+--------|
| isolated      |      |        |
| contiguous    |      |        |
| fused         |      |        |
|---------------+------+--------|
| heterogeneous | dual | plural |
|---------------+------+--------|
| isolated      |      |        |
| contiguous    |      |        |
| fused         |      |        |

*** Number
Number communicates how many instances of a stem are involved in the sentence's action.
| Value       | Definition                     |
|-------------+--------------------------------|
| Singular    | individual                     |
| Dual        | pair                           |
| Plural      | group                          |
*** Connectedness
Connectedness describes the spatiotemporal proximity of the items named by the stem.
| Value      | Definition         |
|------------+--------------------|
| Isolated   | separate           |
| Contiguous | adjacent, touching |
| Fused      | attached, combined |
*** Disposition
Disposition conveys the similarities of use, purpose, or condition
among members of a set.
| Name         | Definition                     |
|--------------+--------------------------------|
| Ambivalent   | unknown/irrelevant use/purpose |
| Oppositional | divided/conflicted use/purpose |
| Mutual       | shared use/purpose             |
| Synergetic   | emergent use/purpose           |
*** Composition
Composition describes the similarity or variety of a set.
| Name          | Definition        |
|---------------+-------------------|
| Homogeneous   | uniform members   |
| Heterogeneous | diverse members   |

*** Distribution
Distribution governs whether operations are applied to individual items from a set or the set itself.
Another way to think about Distribution: Conjunctive Distribution /singularizes/ the set.
| Value       | Definition               |
|-------------+--------------------------|
| Disjunctive | each instance separately |
| Conjunctive | all instances together   |

*** Envelope
Envelope identifies the spatiotemporal limits and dynamics of the set.
Note: I have Envelope scope outside of distribution.
Thus, by varying Distribution, we can refer to the beginning of the set, or the beginning of each member of the set.

| Value      | space                                    | time                     |
|------------+------------------------------------------+--------------------------|
| Partial    | part                                     | phase, moment, era of... |
| Holistic   | all                                      | (whole) duration of...   |
| Initial    | (spatial) beginning, first in a sequence | (beginning) beginning    |
| Terminal   | (spatial) end, last in a sequence        | (temporal) end           |
| Augmentive | physical/directional increase            | developing/becoming      |
| Diminutive | physical/directional decrease            | decaying/ceasing-to-be   |

*** Quantification

| Value       | Definition                      |
|-------------+---------------------------------|
| Existential | "there exists...", at least one |
| Universal   | every instance                  |

*** Vagueness
| Value     | Definition                                                       |
|-----------+------------------------------------------------------------------|
| Vague     | "something like", "what passes for"; questionable set membership |
| Non-Vague | clear set membership                                             |

** Telicity
Telicity differentiates between goal- and process-driven verbs.
| Value  | Definition                             |
|--------+----------------------------------------|
| Telic  | goal-driven, completable action        |
| Atelic | process-driven, non-completable action |
** Comparison
| Name | Definition |
|------+------------|
|      |            |
** Domain
Domain selects the context in which the word is deployed.
| Value         | Definition            |
|---------------+-----------------------|
| Material      | objective             |
| Social        | cultural/personal     |
| Metaphorical  | analogical/rhetorical |
| Philosophical | gestalt               |
*** Material
The Material Domain refers to physical reality of sensible objects.
*** Social
The Social Domain draws attention to the social or cultural dimensions of the subject of discussion.
*** Metaphorical
The Metaphorical Domain considers the analogical, rhetorical, or significative use of a word, rather than its literal definition.
*** Philosophical
The Philosophical Domain considers the full historical and philosophical range of meanings of a word.
** Discourse categories
*** What is meant by a 'discourse category'?
Conversation relates two logically distinct contexts:
1. the content or subject matter of our our conversation, and
2. the people involved in having the conversation; speaker and
   audience plus the performative, rhetorical or communicative actions
   performed between them.

I will call the former 'content level' and the latter 'discourse
level'. While persons and events might coincide between these two
levels, they are indeed very different and the grammar of the language
should reflect this fact.

As an extreme example of overlap between the contexts, someone might
make a sandwich and narrate to themselves every step of the
process: "I slice some bread. I spread peanut butter on one slice and
jelly on another slice..."

In this case, the same individual is the subject spoken about at the
content level, and both speaker and audience at the discourse
level. The former is a description of something in the world, in this
case the activity of the speaker as they assemble a sandwich, while
the latter is simply a person talking to themselves. We can change the
discourse context independently, for instance by having the speaker
use the same series of utterances as a demonstration or tutorial of
how to make a sandwich.

If the two contexts share persons or events, they can be often
distinguished by time, modalization, and role. We often speak about
our past or possible future selves. For example, when giving a
command, "(You) spread peanut butter on the bread", the content is a
possible future state where the addressee is performing the named
action. The discourse level is an instruction or command.

Even if, as in our example of narrating the assembly of a sandwich,
there is no difference in time and modalization, we can make the
distinction that at the content level there is a sandwich maker, and
at the discourse level there is a speaker and a listener. The fact
that all three are the same person in no way diminishes our ability to
differentiate what that person is doing in each role (making a
sandwich, vs. speaking/listening).

*** Illocution
**** What does the speech *do*?
The view I want to adopt here is that all language is performative:
every utterance *does something*.  Truth claims are only one kind of
speech act that happens to have received preferential treatment at the
hands of the logicians. But let us not be fooled: even a simple claim
like, "The sky is blue" entails a new fact about the world. Namely it
is now true that "I claim that the sky is blue".

And these facts about what people claim to be true have important
consequences. It is on their basis that we call someone honest or
dishonest, well- or ill-informed, fair-minded or hypocritical, and so
on. Because we are committed to truth, and there is a whole system of
trust and consensus reality interwoven with it, it makes sense to mark
truth claims as a distinct category.

Illocution can only be used to indicate speech acts made in the first
person. I cannot, of instance, use Illocution to say, "Alice
instructed Bob to make a sandwich." For speech acts made by 2nd and
3rd persons, the language will require verbs for "warn", "promise",
"inform", "command", and so on. It is therefore sufficient to have
only two values for Illocution: Assertive and Performative. The former
marks truth claims and latter all other speech acts.

Consider these:

#+begin_quote
"I warn you"+Assertive

"I warn you"+Performative
#+end_quote

The first is a claim, it presumes that some other sign or speech act
carries the warning, while the sentence merely asserts that warning
takes place. The second really is the warning. And having only two
values means an open class of verbs naming speech acts that may be
either mentioned (in Assertive sentences) or used (in Performative
sentences).

It may be helpful here to consider that a sentence like, "I warn
you..." seems like a speech act, while "I warn them..." is a claim. "I
warn them..." *cannot* be the same sentence the speaker used as a
warning—otherwise it would refer to the recipient of the command in
the 2nd person: "I warn *you*..."

*** Expectation
Now for the category of Expectation, it's purpose is to mark what kind
of response the speaker desires from their audience. Broadly speaking,
the three expectations work as generalized versions of the classic
trio of sentence purposes in English (Declarative, Interrogative, and
Imperative), and may also be thought of as corresponding to an
expected "channel" in which the response will take place (as thought,
speech, and action).

|                   | Cognitive   | Discursive    | Motive     |
|-------------------+-------------+---------------+------------|
| intended response | thought     | speech        | action     |
| sentence purpose  | declarative | interrogative | imperative |

Expectation is not to be used for things like polite
"question-commands" or rhetorical questions: rather, it should mark
how the speaker actually intends their conversational partner to
respond. The reason for this is that the verbs naming speech acts
(which have replaced many of the Illocutions) can be used in tandem
with Expectation and Illocution to produce both direct and indirect
commands.

Speech acts like warnings and commands may be, but are not
necessarily, truth claims. Consider the following utterances:

#+begin_quote
If you touch the stove, you will get burned.

I warn you not to touch the stove.
#+end_quote

The first sentence seems like a truth claim, but it can be *used* as a
warning. The second is explicitly a warning, but it may be only the
*mention* of a warning previously given—in other words, it may be an
assertion that a warning was issued.

|            | Assertive                                              | Performative                                                           |
|------------+--------------------------------------------------------+------------------------------------------------------------------------|
| Cognitive  | truth claim inviting only mental consideration         | stipulation or declaration entailing cognitive change (c.f. =let x = y=) |
| Discursive | truth claim inviting rebuttal, comment, or explanation | request for comment                                                    |
| Motive     | truth claim inviting listener to take action           | warning, command, specific call to action                              |

Consider, for example, the following sentence in each of the 6
Illocution×Expectation combinations listed in the preceding
table. This sentence does not name a speech act, so it demonstrates
the power and flexibility of the new Illocution×Expectation scheme.

#+begin_quote
There is toilet paper on your shoe.
#+end_quote

|            | Assertive                                                            | Performative                                                        |
|------------+----------------------------------------------------------------------+---------------------------------------------------------------------|
| Cognitive  | I claim there is toilet paper on your shoe.                          | Consider yourself informed that there is toilet paper on your shoe. |
| Discursive | Comment on the toilet paper on your shoe.                            | Isn't that toilet paper on your shoe?                               |
| Motive     | I claim there is toilet paper on your shoe, (do something about it). | Do something about the toilet paper on your shoe!                   |

Note the capacity here for making indirect, but clearly marked
commands and questions. Honestly this system is so alien to me that
I'm not sure if it will work, but it also manages to cover all the
bases I can think of.  Also note that you can turn those into explicit
commands and questions simply by adding the right verb, so instead of
"There is toilet paper on your shoe"+Performative+Motive, you could
easily say, "You clean your shoe"+Performative+Motive to make explicit
what you want your listener to do.

*** Evidentials
Evidentials mark the source of information presented in an utterance.
The categories of evidence are chosen to mark clear distinctions in categories of evidence while discouraging escalation of claims.
Thus, remembered sensory knowledge is treated differently than present sensory knowledge, but all unverifiable first-person claims share a category.
All forms of evidence can be unreliable, and different thinkers disagree about which are most valid under which circumstances.
Persons can be mistaken, deceived, or motivated in their thinking, and this language must not shy away from that.

| Name             | Gloss                                   | Description                                                            |
|------------------+-----------------------------------------+------------------------------------------------------------------------|
| Credential       | "I believe/assume/posit/hypothesize..." | belief with unspecified evidence                                       |
| Observational    | "I observe..."                          | present sensory knowledge                                              |
| Recollective     | "I remember..."                         | past sensory knowledge                                                 |
| Reportive        | "Someone informed me..."                | 2nd-hand knowledge/hearsay from specific informants                    |
| Conventional     | "I know through cultural means..."      | general cultural knowledge                                             |
| Inferential      | "I conclude..."                         | result of rational process (however informal)                          |
| Analogical       | "I analogize..."                        | result of comparison, induction, extrapolation, or ostension           |
| Non-Apprehensive | "I know by negative means..."           | conclusion from absence of evidence, failure/absurdity of alternatives |
| Imaginary        | [non-claim: unreal]                     | statement not thought to be true, (used in conjunction with mood)      |

**** Credential
#+begin_quote
I think...
#+end_quote

The Credential Evidentiality marks claims supported only by private first-person evidence.
It covers hunches, intuitions, beliefs, opinions, unsubstantiated theories, and forms of so-called direct knowledge.
These diverse means of acquiring knowledge fall under a single evidentiary category so that no one can "escalate" the trustworthiness of first person information.
For example, if we hold that mystical visions carry more weight than mere opinion, an unscrupulous person could claim that their private hunch was in fact prophesy.
The purpose of evidentials is to establish the grounds upon which the conversants can come to a shared understanding of reality.
It is therefore desirable not to distinguish between evidentials which are not amenable to 2nd or 3rd person verification.
Most schools of thought agree that Credential is one of the weakest forms of evidence.
However, mystical and individualist thinkers may place it above the rest as "conscience" or "conviction", or even "revelation".

- I think they are up to some mischief.
- The gods have shown me the future.
- Nurture is as influential as nature.

**** Observational
#+begin_quote
I observe...
#+end_quote

The Observational Evidentiality expresses present sensory knowledge.
Observational is to be used when the speaker can see, hear, smell, taste, or feel the subject of conversation.
It is the evidentiary form par excellance of the empricisists.
However it is used less frequently than the Recollective because of the infrequency with which claims can be immediately verified by sense.

- The ground is soft.
- She burnt the toast.
- There are four lights.

**** Recollective
#+begin_quote
I remember...
#+end_quote

The Recollective Evidentiality indicates remembered sensory knowledge.
This evidentiality is separate from Observational because of memory's documented unreliability.
Though generally considered weaker than the Observational, the efficacy of sense memory is a presumption of any empiricist philosophy.

- They drove off in a green truck.
- He sometimes wears a hat.
- The trail begins nearby.

**** Reportive
#+begin_quote
My source informs me...
I was taught...
#+end_quote

The Reportive Evidentiality claims one or more specific individuals as knowledge sources.
Using Reportive indicates that the speaker could attribute the claim to an identifiable person or text.
(Though of course the speaker is under no obligation to divulge their informant's identity.)
Statements in the Reportive are held to be as trustworthy as the source of the information.

- Searing meat doesn't seal in the juices.
- There are billions and billions of stars.
- Nobody expects the Spanish Inquisition.

**** Conventional
#+begin_quote
They say...
I read somewhere...
#+end_quote

The Conventional Evidentiality marks knowledge issuing from non-specific second-hand sources.
It is used for second-hand evidence that cannot be attributed to an individual.
This includes matters of socially determined knowledge.

- You know what they say...
- Augustine is the patron saint of brewers.
- Nevada is part of the United States.
- Carbohydrates are bad for one's health.

**** Inferential
The Inferential Evidentiality attributes knowledge to a process of (possibly informal) reasoning.
Utterances marked Inferential are held to be as valid as their most disputable premise or means of inference.
Use of Inferential suggests that the speaker could make their reasoning public.

- They must have left in a hurry.
- Only the guilty have reason to fear.

**** Analogical
#+begin_quote
I analogize...
#+end_quote

The Analogical Evidentiality attributes knowledge to analogy, comparison, ostention, generalization, particularization, or induction.
Some philosophies consider analogical reasoning problematic, while others claim all other sources of knowledge are ultimately derived from comparison.

- Other animals have first-person experiences.
- Gravity is ubiquitous.
- Primes continue without end.

**** Non-Apprehensive
#+begin_quote
Lack of evidence suggests... 
#+end_quote

The Non-Apprehensive indicates that an absence of evidence or failure or contradiction of alternatives is the source of the knowledge.
Opinions are divided on the validity of knowledge acquired through this means.

This evidentiality would be used in statements like the following:

- There are no interstellar civilizations.
- Supernatural beings do not exist.
- This house is free of tigers.
- A round square cannot be constructed.

**** Imaginary
#+begin_quote
I imagine...
#+end_quote

The Imaginary Evidential marks statements the speaker does not know or believe to be true.
It is used in combination with irrealis moods to discuss states of affairs contrary to fact.

- Water lilies fly.
- The old gods still dwell in the wild, lonely places.
- All swans are white.
- If I were a rich man...
